---
- name: Install apache
  apt:
   name: apache2
   state: present

- name: Apache listen on port
  lineinfile:
   dest: /etc/apache2/ports.conf
   regexp: '^Listen'
   line: Listen 81

- name: Configure Apache
  ansible.builtin.template:
   src: apache.conf.j2
   dest: /etc/apache2/apache2.conf
  notify: 
   - restart apache

