---
- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: restart apache
  service: name=apache2 state=restarted enabled=yes

- name: restart mysql
  service: name=mysql state=restarted
